# -*- mode: ruby -*-
# vi: set ft=ruby :

targets = {
  centos6: {
    box: 'centos/6',
  },
  centos7: {
    box: 'centos/7',
  },
  debian7: {
    box: 'debian/wheezy64',
  },
  debian8: {
    box: 'debian/jessie64',
  },
  ubuntu14: {
    box: 'ubuntu/trusty64',
  },
  ubuntu16: {
    box: 'ubuntu/xenial64',
  },
}

Vagrant.configure('2') do |config|
  config.vm.provider 'virtualbox' do |vbox|
    vbox.cpus   = 1
    vbox.memory = 512
  end

  targets.each do |name, args|
    name = name.to_s
    config.vm.define name do |build|
      build.vm.box      = args[:box]
      build.vm.hostname = name
    end
  end
end
